include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # ===== Dead Code =====
    # Replace warning with error to make sure that we don't have any dead code in our project.
    unused_local_variable: warning
    unused_field: warning
    unused_element: warning
    unnecessary_import: warning

linter:

  rules:
    # ===== Performance =====
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

    # ===== Clean Code =====
    always_declare_return_types: true
    avoid_print: true
    prefer_final_fields: true
    unnecessary_this: true

    # ===== Readability =====
    prefer_single_quotes: false
    prefer_double_quotes: true
    require_trailing_commas: true

    # ===== Safety =====
    avoid_unnecessary_containers: true
    avoid_redundant_argument_values: true
    unnecessary_null_checks: true
